### ISSUE TITLE
/roll wild output for results of 5 is incorrect

### ISSUE THREAD

**Issue by Geeks-For-The-Geek-God** [kavita-p/sparks.rs#3]
The "/roll wild" command is outputting results of 5 as a Triumph rather than a Conflict.

![Screenshot 2023-02-04 121300](https://user-images.githubusercontent.com/124622960/217059729-52440238-5854-45ad-ba58-35c0777305fe.png)

**Comment by kavita-p** [comment]
fixed! had the success tiers written down all wrong for some reason, but sparks is returning them correctly now.
